from setuptools import find_packages, setup

setup(
    name="fracture_plotter",
    version="0.1.0",
    description="A Python based project for plotting fracture results.",
    author="Samuel Adolfo Cruz Alegría",
    author_email="cruzas@usi.ch",
    maintainer="Arancia Malaspina",
    maintainer_email="arancia.malaspina@usi.ch",
    license="LICENSE",
    license_files=["LICENSE"],
    packages=find_packages(where="src"),
    package_dir={"": "src"},
    install_requires=[
        "bottleneck==1.3.7",
        "cryptography==43.0.0",
        "cycler==0.11.0",
        "cffi==1.17.1",
        "fonttools==4.51.0",
        "matplotlib==3.9.3",
        "numpy==1.26.4",
        "pandas==2.2.2",
        "pdfminer.six==20221105",
        "pdfplumber==0.9.0",
        "platformdirs==3.10.0",
        "pooch==1.7.0",
        "pypdf2==3.0.1",
        "pysocks==1.7.1",
        "python-dateutil==2.9.0.post0",
        "pytz==2024.1",
        "requests==2.32.2",
        "scipy==1.10.1",
        "six==1.16.0",
        "tornado==6.4.1",
        "typing-extensions==4.12.2",
        "urllib3==2.2.2",
        "wand==0.6.10",
        "zipp==3.17.0",
        "charset-normalizer==2.0.4",
        "certifi==2024.8.30",
        "idna==3.7",
        "pycparser==2.21",
        "pyparsing==3.0.9",
        "packaging==24.1",
    ],
)
